{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "kubernetes-ai-ops-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}