{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-ai-ops-agent.serviceAccountName" . }}
  labels:
    {{- include "kubernetes-ai-ops-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- if .Values.serviceAccount.rbac.create }}
# ClusterRole with permissions to access various Kubernetes resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-ai-ops-agent.fullname" . }}-role
  labels:
    {{- include "kubernetes-ai-ops-agent.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.serviceAccount.rbac.rules | nindent 2 }}
---
# ClusterRoleBinding to bind the ServiceAccount to the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-ai-ops-agent.fullname" . }}-role-binding
  labels:
    {{- include "kubernetes-ai-ops-agent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-ai-ops-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubernetes-ai-ops-agent.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
